from typing import Any, Dict, List, Optional, Set

class MatchStatus:
    UPCOMING: str
    COMPLETED: str
    CANCELLED: str
    POSTPONED: str
    INTERRUPTED: str

class MatchListFilter:
    def start_date(self, date: str) -> "MatchListFilter": ...
    def end_date(self, date: str) -> "MatchListFilter": ...
    def exclude_statuses(self, statuses: Set[str]) -> "MatchListFilter": ...
    def fetch_filtered_matches(self, api_client: "FogisApiClient") -> List[Dict[str, Any]]: ...

class FogisApiClient:
    def __init__(self, username: str, password: str) -> None: ...
    def login(self) -> bool: ...
